### ISSUE TITLE
Post.create() fails with json deserialization exception

### ISSUE THREAD

**Issue by abstruction** [amarpersaud/python-jplaw#16]
**Describe the bug**
Post.create() fails with json deserialization exception

**To Reproduce**
log into a Lemmy instance (Lemmy.world in this case)
get a community id
attempt 
data = lem.Post.create(id, 'Testing', '1, 2, 3')

**Expected behavior**
Post should go up, data should come back

**Screenshots**
The exception:  
`
Traceback (most recent call last):
  File "<pyshell#3>", line 1, in <module>
    data = lem.Post.create(id, 'Testing', '1,2,3')
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/jplaw/post.py", line 90, in create
    res = self._req.lemmyRequest("createPost", instance=instance, form=form, optional=optional, auth=True)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/jplaw/requestor.py", line 89, in lemmyRequest
    return self.request((API_PATH[function]["method"]), self.apiURL(instance=instance, path=(API_PATH[function]["path"])), form)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/jplaw/requestor.py", line 52, in request
    raise Exception(response.text)  # Adjust this according to how your API returns errors
Exception: Json deserialize error: invalid type: string "false", expected a boolean at line 1 column 75  
`

**Desktop (please complete the following information):**
 - OS: macOS Ventura

**Comment by amarpersaud** [comment]
Context for this issue: Some of the API functions which take a boolean were expecting "true" or "false" while others expected a boolean 0/1. In fixing the "true"/"false" expecting functions, it broke others that previously worked. I disabled the conversion for boolean values and it should work. Merge should be through in a bit, but might break some other functions.

**Comment by abstruction** [comment]
Working now, thanks!
