### ISSUE TITLE
Cannot get comment list

### ISSUE THREAD

**Issue by notBradPitt** [amarpersaud/python-jplaw#30]
I get the following error:
```
Traceback (most recent call last):
  File "xxx", line 12, in <module>
    comments = lemmy.Comment.list(post_id=post["post"]["id"], sort="Top")
  File "xxx\jplaw\comment.py", line 219, in list
    "comment_id"        : comment_id,
NameError: name 'comment_id' is not defined. Did you mean: 'community_id'?
```

I've noticed several errors:
- Comment ID is put into `form` instead of `optional`, which I think implies that it is required (it's not)
- Variable `type_` doesn't exist
- Response doesn't contain `comment_view`

My solution to the above problems was:
- Removing `comment_id` entirely from `form` since the `getComments` doesn't seem to accept `comment_id` parameter anyway
- Replacing `type_` with `comment_type`. `type_` is the parameter passed to the API while `comment_type` is the parameter accepted by the `list()` functtion.
- Replacing `comment_view` with `comments`. Not sure where this came from, the response I received only contains `comments` and not `comment_view`

```
form = {
            }
        optional={
            "type"              : comment_type      ,
            "sort"              : sort              ,
            "max_depth"         : max_depth         ,
            "page"              : page              ,
            "limit"             : limit             ,
            "post_id"           : post_id           ,
            "community_id"      : community_id      ,
            "community_name"    : community_name    ,
            "parent_id"         : parent_id         ,
            "saved_only"        : saved_only        ,
            }
       
        res = self._req.lemmyRequest("getComments", instance=instance, form=form, optional=optional, auth=auth)
        return res["comments"]
```

**Comment by amarpersaud** [comment]
Original merge request closed because the way I have workflows set up is weird. I merged it into a dev branch first and then merged it into main. I left a v0.1.11 dev branch open for pull requests in the future 

The comment issue should be fixed now and I added some of the changes made since I last touched this

**Comment by notBradPitt** [comment]
Thank you. Problem fixed, really appreciate it! 👏
